name: tests backend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Démarrer le PostgreSQL déjà installé dans GitHub Actions
      - name: Start built-in PostgreSQL
        env:
          PASSWORD: 123456789
          DATABASE: emotion_data
        run: |
          sudo systemctl start postgresql
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '${PASSWORD}';"
          sudo -u postgres psql -c "CREATE DATABASE \"${DATABASE}\";"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          USER: postgres
          PASSWORD: 123456789
          HOST: localhost
          PORT: 5432
          DATABASE: emotion_data
        run: |
          pytest -v
